schemaVersion: 1.1.0
locale: "en"
groupings:
  - title: "OCI Container Registry"
    variables:
    - compartment_ocid
    - display_name
    - is_public

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    title: Target Compartment
    description: The target compartment id where to deploy the registry
    required: true

  display_name:
    type: string
    pattern: '^[a-z0-9]+(?:[-][a-z0-9]+)*\/[a-z0-9]+(?:[-][a-z0-9]+)*$'
    title: Registry name
    description: Registry name. Format: <namespace>/<container-image>
    required: true
    
  is_public:
    type: boolean
    title: Public access
    description: Enable access to the registry from the Internet
    default: false 

